### ISSUE TITLE
Failed to detect gateway to pay

### ISSUE THREAD

**Issue by ns1000** [soom-4th-blockchain/soom-core#1]
I am having this issue:
CGatewayPayments::FillBlockPayee -- Failed to detect gateway to pay

Seems that the masternode synchronization somehow doesn't work? Is this is a settings issue or a bug?

**Comment by ns1000** [comment]
I am running v1.0.2 compiled from git

**Comment by ns1000** [comment]
Fairly sure it has to do with this:
2018-12-11 00:23:16 ProcessMessages(gww, 137 bytes): Exception 'ReadCompactSize(): size too large: iostream error' caught

**Comment by hcdo** [comment]
Please use the source of the master branch.
Other branches may have bugs.

**Comment by hcdo** [comment]
Network protocol version in master branch updated 70209. but, the unpatched v1.0.2 branch.  
gateway version does not match,  gateway serializes the new signature used in protocol version 70210.
We moved v1.0.2 to v1.0.3 and fixed that bug now.
However, There may be more bugs in communication between gateways
